
import sqlite3
from sqlite3 import Error
 

db_file = './walktraceDB.db'
conn = sqlite3.connect(db_file)



conn.execute('''

CREATE TABLE STEPS (

ID BIGINT PRIMARY KEY NOT NULL,

DATE DATETIME NOT NULL,

USERNAME VARCHAR(25) NOT NULL, 

DESC VARCHAR(50),

S1_VALUE INT NOT NULL,
S1_ANOMALY BOOLEAN NOT NULL,

S2_VALUE INT NOT NULL,
S2_ANOMALY BOOLEAN NOT NULL,

S3_VALUE INT NOT NULL,
S3_ANOMALY BOOLEAN NOT NULL,

S4_VALUE INT NOT NULL,
S4_ANOMALY BOOLEAN NOT NULL,

S5_VALUE INT NOT NULL,
S5_ANOMALY BOOLEAN NOT NULL,

S6_VALUE INT NOT NULL,
S6_ANOMALY BOOLEAN NOT NULL,

IS_ANOMALY BOOLEAN NOT NULL

)
''')

print('Base created sycc.')



